#!/bin/bash

date
mysqldump --databases planb_site_live --user=root --password=g33kRul3 > /opt/dbbkup/planb_site.sql
mysqldump --databases planb_forum_live --user=root --password=g33kRul3 > /opt/dbbkup/planb_forum.sql
cp /var/www/rails/planb_blog/db/database.sqlite /opt/dbbkup/planb_blog.sqlite
cd /opt/dbbkup
svn ci -m "database update"
