
        login: &login
          adapter: sqlite3
          database: db/database.sqlite

        development:
          <<: *login

        production:
          <<: *login

        test:
          database: ":memory:"
          <<: *login
        